exp_dir: ./eval_outputs
dataset_name: tapvid_davis_first
dataset_root: /fsx-repligen/shared/datasets/tapvid
checkpoint: ./checkpoints/scaled_offline.pth
grid_size: 5
local_grid_size: 8
num_uniformly_sampled_pts: 0
sift_size: 0
single_point: false
offline_model: true
window_len: 60
n_iters: 6
seed: 0
gpu_idx: 0
local_extent: 50
v2: false
